### ISSUE TITLE
Review routing rule and JS call on `resourcesJson`

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/manager#187]
A refactor is needed on this routing rule  after #150 
```
 $routes->connect(
        '/:object_type/view/:id/resourcesJson/:relation',
         ['controller' => 'Modules', 'action' => 'resourcesJson'],
        ['pass' => ['id', 'relation'], '_name' => 'modules:resourcesJson']
    );
```
no `object_type` and object `id` is needed here, but a simpler API call
also we are not using a `relation` but a `resource` type name

**Comment by didoda** [comment]
Done with https://github.com/bedita/manager/pull/585
