### ISSUE TITLE
View all object fields

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/manager#28]
In `Data / Objects / edit object` display all available attributes like in `Users` details.

Or we should wait for `Design`?

**Comment by edoardocavazza** [comment]
At the moment forms are self generated using the model schema. For core models, they are inline in the script files, but in the future (when the `object_types` route is ready) every model will "download" its schema and its relationships definitions. Until that moment, we could generate the form using the data of model and placing simple inputs for every field (text or number), but it will not work for new entities. Maybe we should wait for the complete API-based solution

**Comment by stefanorosanelli** [comment]
Agreed, we will do it when model schema is available from `/object_types`

**Comment by stefanorosanelli** [comment]
addressed in a new issue... closing
