### ISSUE TITLE
Handle requests to save actions when session is expired

### ISSUE THREAD

**Issue by xho** [bedita/manager#357]
Trying to save an object when session is expired:

1. first redirects the user to the login page;
2. than there is another redirect to the original save action after a successful login.

This throws errors since information is lost in redirects.

- As a quick solution I would suggest to avoid redirects to save actions after login.

- For a more articulate solution I would keep the information about the session (if it is still live) in the javascript environment, in order to show a blocking popup containing an AJAX login form when the session is expired (and force a new login before proceeding).

**Comment by stefanorosanelli** [comment]
In #359 a quick solution has been implemented
A new issue should be opened for a more articulated solution to handle expired sessions.
