### ISSUE TITLE
Delete operation on a translation should trash it, not unlink

### ISSUE THREAD

**Issue by xho** [bedita/manager#425]
Now the remove translation button removes only the relation.
This way the existing translation remains as an orphan.
It should be deleted (after confirm dialog).

**Comment by didoda** [comment]
this could have been fixed in api (bedita/bedita:4-cactus or bedita/php-sdk)

I tried in a local environment:

 - create a document
 - create a translation of the document 
 - delete the translation
 - check on "translations" table: it's empty

May we consider it fixed? @xho

**Comment by stefanorosanelli** [comment]
Works as expected now
