### ISSUE TITLE
Side panel for adding relationships has no overflow

### ISSUE THREAD

**Issue by le0m** [bedita/manager#429]
When adding relationships with objects through the side panel, the confirm button goes outside the page if there are too many objects and there is no scrollbar (screenshot is censored).

![Schermata da 2020-07-13 17-12-26](https://user-images.githubusercontent.com/10656716/87325174-66622980-c531-11ea-940b-8443075ba3c9.jpg)

**Comment by xho** [comment]
I think it was solved in latest UI refactor: https://github.com/bedita/manager/pull/428

**Comment by le0m** [comment]
Sure it is ^^
