### ISSUE TITLE
Missing "users" checkbox

### ISSUE THREAD

**Issue by fquffio** [bedita/manager#49]
From "Objects" view I can see checkbox for all object types but "users", yet users are still listed.

I don't know if it is supposed to be this way, or it's a bug.

![image](https://user-images.githubusercontent.com/7108146/31269842-3fb4c7e2-aa82-11e7-9838-00e254ceadac.png)

**Comment by stefanorosanelli** [comment]
it's a bug, it will be fixed in #22 - once #36 is merged

**Comment by fquffio** [comment]
Ok, sorry for duplicate.
